# Build and test solution
name: Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  actions: read
  checks: write

jobs:
  Build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" || true

    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test Results
        path: "**/test-results.trx"                            
        reporter: dotnet-trx
        fail-on-error: true

    - name: Increment Version
      if: ${{ github.event_name == 'push' && success() }}
      shell: pwsh
      run: |
        ./scripts/incrementVersion.ps1

    - name: Commit Version
      uses: stefanzweifel/git-auto-commit-action@v5
      if: ${{ github.event_name == 'push' && success() }}
      with:
        commit_message: Automated version update [skip ci]

